version: "3"
services:
  wine-cellar-app:
    image: wine-cellar
    build:
      context: .
      args:
        - APP_NAME=${APP_NAME}
        - APP_REPOSITORY=${APP_REPOSITORY}
    ports:
      - "${EXTERNAL_PORT}:3000"
    volumes:
      - wine-cellar-data:${DB_FOLDER}
      - wine-cellar-log:${LOG_FOLDER}
      - wine-cellar-web:${WEB_FOLDER}
    environment:
      - NODE_ENV=${NODE_ENV}
      - TOKEN_SECRET=${TOKEN_SECRET}
      - LOG_LEVEL=${LOG_LEVEL}
      - DB_FOLDER={DB_FOLDER}
      - LOG_FOLDER=${LOG_FOLDER}
